package com.ceyentra.sm.enums;

public enum MealTypes {
    BREAKFAST, LUNCH, DINNER, TEA_TIME, DRINK, SOUP, BIRIYANI, BBQ, STARTERS,
    CHICKEN, INTERNATIONAL, EXTRA, SANDWICH, DESSERT, FRESH_JUICE
}
